#!/bin/bash
# Inspect an Ascend NPU docker image and emit repo/knowledge/images/<slug>.md.
# See repo/skills/npu-image-inspect/SKILL.md for scope, contract, gotchas.
#
# Usage:
#   inspect-ascend-image.sh <image-ref> [--out path.md] [--keep-tmp] [--python-prefix /usr/local/pythonX.Y.Z]

set -euo pipefail

IMAGE=""
OUT=""
KEEP_TMP=0
PY_PREFIX=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    --keep-tmp) KEEP_TMP=1; shift ;;
    --python-prefix) PY_PREFIX="$2"; shift 2 ;;
    -*) echo "unknown arg: $1" >&2; exit 2 ;;
    *) IMAGE="$1"; shift ;;
  esac
done
if [[ -z "${IMAGE}" ]]; then
  echo "usage: $0 <image-ref> [--out path.md] [--keep-tmp] [--python-prefix PATH]" >&2
  exit 2
fi

# Slugify the image ref for default output path.
slug="$(echo "${IMAGE}" | tr '/:@+' '----' | tr -cd '[:alnum:]-.')"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${OUT:-${REPO_ROOT}/knowledge/images/${slug}.md}"
mkdir -p "$(dirname "${OUT}")"

TMP="$(mktemp -d -t npu-image-inspect.XXXXXX)"
CID=""
cleanup() {
  [[ -n "${CID}" ]] && docker rm "${CID}" >/dev/null 2>&1 || true
  if [[ ${KEEP_TMP} -eq 0 ]]; then rm -rf "${TMP}"; else echo "kept tmp: ${TMP}"; fi
}
trap cleanup EXIT

# Image config (env, entrypoint, cmd).
docker inspect "${IMAGE}" --format '{{json .Config}}' > "${TMP}/config.json"

# Create a container to copy from. We never start it.
CID=$(docker create --name "inspect-${slug:0:40}-$$" "${IMAGE}" /bin/true)

# Locate the python prefix inside the image by trial.
if [[ -z "${PY_PREFIX}" ]]; then
  for p in python3.11.14 python3.11.13 python3.11 python3.10; do
    if docker cp "${CID}:/usr/local/${p}/bin/python3" "${TMP}/_py_probe" >/dev/null 2>&1; then
      PY_PREFIX="/usr/local/${p}"
      rm -f "${TMP}/_py_probe"
      break
    fi
  done
fi
if [[ -z "${PY_PREFIX}" ]]; then
  echo "ERROR: could not find python under /usr/local/python* in the image" >&2
  exit 4
fi

# Derive python<M.m> from basename for site-packages path.
pyver=$(basename "${PY_PREFIX}" | sed 's/^python//' | cut -d. -f1-2)
SITE="${PY_PREFIX}/lib/python${pyver}/site-packages"

# Copy site-packages out (this is the bulk).
if ! docker cp "${CID}:${SITE}" "${TMP}/site-packages" >/dev/null 2>&1; then
  echo "ERROR: could not docker cp ${SITE} out of image (wrong python path?)" >&2
  exit 5
fi

# Derive pip-freeze from .dist-info dir names.
ls "${TMP}/site-packages" | awk '/\.dist-info$/{ sub(/\.dist-info$/, ""); print }' | sort > "${TMP}/pip-freeze.txt"

# Triton-ascend integrity check (NPU-BUG-001).
triton_ascend_entry=$(grep -E '^triton[_-]ascend-' "${TMP}/pip-freeze.txt" | head -1 || true)
triton_init_present=0
[[ -f "${TMP}/site-packages/triton/__init__.py" ]] && triton_init_present=1

# Parse config.
ascend_home=$(python3 -c "
import json
c = json.load(open('${TMP}/config.json'))
env = {kv.split('=',1)[0]: kv.split('=',1)[1] for kv in c.get('Env',[]) if '=' in kv}
print(env.get('ASCEND_HOME_PATH', env.get('ASCEND_TOOLKIT_HOME','')))
")
entrypoint=$(python3 -c "import json; c=json.load(open('${TMP}/config.json')); print(c.get('Entrypoint'))")
cmd=$(python3 -c "import json; c=json.load(open('${TMP}/config.json')); print(c.get('Cmd'))")

total_py=$(wc -l < "${TMP}/pip-freeze.txt")

# apt count.
apt_count=0
if docker cp "${CID}:/var/lib/dpkg/status" "${TMP}/dpkg-status" 2>/dev/null; then
  apt_count=$(grep -c '^Package: ' "${TMP}/dpkg-status" 2>/dev/null || echo 0)
fi

interesting=$(grep -iE '^(torch|torch_npu|torch-npu|transformers|vllm|vllm_ascend|vllm-ascend|triton|triton_ascend|triton-ascend|accelerate|tensordict|torchdata|ray|peft|datasets|numpy|pyarrow|safetensors|tokenizers|huggingface_hub|pillow|jinja2|psutil|pyyaml|mathruler|qwen_vl_utils|flash-attn|liger-kernel|hf_transfer|einops|bytecode|pybind11|sentencepiece|compressed_tensors|megatron_core|mindspeed|mbridge)[_-][0-9]' "${TMP}/pip-freeze.txt" | head -60 || true)

# Emit the markdown doc.
{
  echo "# ${IMAGE} — image inventory"
  echo
  echo "Generated by \`repo/scripts/inspect-ascend-image.sh\` on $(date -I)."
  echo
  echo "## Runtime environment"
  echo
  echo "- **Image**: \`${IMAGE}\`"
  echo "- **Python prefix**: \`${PY_PREFIX}\`"
  echo "- **ASCEND_HOME_PATH**: \`${ascend_home}\`"
  echo "- **Entrypoint**: \`${entrypoint}\`"
  echo "- **Cmd**: \`${cmd}\`"
  echo
  echo "## Triton-ascend integrity check (NPU-BUG-001)"
  echo
  if [[ -n "${triton_ascend_entry}" && ${triton_init_present} -eq 0 ]]; then
    echo "> :warning: **NPU-BUG-001 detected**: \`${triton_ascend_entry}\` is installed (dist-info present) but \`${SITE}/triton/__init__.py\` is **missing**. \`import torch_npu\` will fail via the \`torch._inductor\` chain with \`ImportError: cannot import name 'Config' from 'triton'\`."
    echo
    echo "**Fix**: add this early layer to downstream Dockerfiles:"
    echo
    echo '```dockerfile'
    printf 'RUN pip install --no-cache-dir --force-reinstall --no-deps %s || \\\n' "$(echo ${triton_ascend_entry} | sed 's/-/==/')"
    printf '    pip install --no-cache-dir --force-reinstall --no-deps \\\n'
    printf '      --index-url https://mirrors.huaweicloud.com/ascend/repos/pypi %s\n' "$(echo ${triton_ascend_entry} | sed 's/-/==/')"
    echo '```'
  elif [[ -n "${triton_ascend_entry}" ]]; then
    echo "OK: \`${triton_ascend_entry}\` installed and \`triton/__init__.py\` is present."
  else
    echo "No triton-ascend in this image."
  fi
  echo
  echo "## Core ML stack (versions from dist-info)"
  echo
  echo '```'
  echo "${interesting}"
  echo '```'
  echo
  echo "## Totals"
  echo
  echo "- Python distributions: **${total_py}**"
  echo "- APT packages: **${apt_count}**"
  echo
  echo "## Full pip freeze"
  echo
  echo "<details><summary>All ${total_py} entries</summary>"
  echo
  echo '```'
  cat "${TMP}/pip-freeze.txt"
  echo '```'
  echo
  echo "</details>"
} > "${OUT}"

echo "wrote ${OUT}"
