"""snapshot_current.py — emit YAML baseline of current fork/skill state.

Per TEST_SAFETY_FEEDBACK_DESIGN.md v4 §5 + P0k:

  Reads UPSTREAM_FORKS.md ledger + repo state and emits a baseline
  snapshot YAML. Snapshot can later be diffed against current state
  to detect regression (e.g., fork branch reverted, outcome changed,
  artifact deleted).

  Schema: claim-manifest-compatible subset + as_of_date +
  auto_advance_branches whitelist.

Usage:
  python3 snapshot_current.py --repo-root <r> > docs/_meta/snapshots/<date>_baseline.yaml

Author: T31.10 (P0k implementation).
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path
from typing import Any, Dict, List


def _parse_upstream_forks(forks_md: Path) -> List[Dict[str, Any]]:
    """Parse the UPSTREAM_FORKS.md table into a list of dicts.

    Format expected (per docs/_meta/UPSTREAM_FORKS.md):
      | Upstream | Personal fork | Active branch | Latest case status | PR_MATERIAL |
      | ... | ... | ... | ... | ... |
    """
    if not forks_md.exists():
        return []

    rows: List[Dict[str, Any]] = []
    lines = forks_md.read_text().splitlines()
    in_table = False
    header: List[str] = []

    for line in lines:
        s = line.strip()
        if not s.startswith("|"):
            in_table = False
            continue
        # Header detection (the first table row with "Upstream" column)
        cells = [c.strip() for c in s.strip("|").split("|")]
        if not in_table and any("Upstream" in c for c in cells):
            header = cells
            in_table = True
            continue
        # Separator row ---|---|...
        if in_table and all(set(c) <= set("-: ") for c in cells if c):
            continue
        # Data rows
        if in_table and len(cells) == len(header):
            row = dict(zip(header, cells))
            rows.append(row)
    return rows


def _extract_branch_from_link(link_text: str) -> str:
    """Markdown link like `[name](url) (extra)` → extract branch ref.

    Look for `ascend-port/...` or `ascend-port-...` substring.
    """
    m = re.search(r"(ascend-port[-/][A-Za-z0-9._-]+)", link_text)
    return m.group(1) if m else ""


def _emit_yaml_block(name: str, fields: Dict[str, Any], indent: int = 2) -> List[str]:
    """Manually emit a YAML mapping block (deterministic, no PyYAML)."""
    pad = " " * indent
    out = [f"{' ' * (indent - 2)}- skill: {name}"]
    for k, v in fields.items():
        if isinstance(v, str):
            # Quote if contains special chars
            if any(c in v for c in ":#[]{}*&!,'\""):
                escaped = v.replace('"', '\\"')
                out.append(f'{pad}{k}: "{escaped}"')
            else:
                out.append(f"{pad}{k}: {v}")
        elif v is None:
            out.append(f"{pad}{k}: null")
        else:
            out.append(f"{pad}{k}: {v}")
    return out


def snapshot(repo_root: Path) -> str:
    """Return the YAML baseline text for current repo state."""
    forks_md = repo_root / "docs" / "_meta" / "UPSTREAM_FORKS.md"
    rows = _parse_upstream_forks(forks_md)

    today = dt.date.today().isoformat()
    out = [
        f"# Regression baseline snapshot — generated by snapshot_current.py",
        f"as_of_date: {today}",
        f"generated_by: src/scripts/safety/snapshot_current.py",
        f"schema_version: \"1.0\"",
        f"",
        f"# auto_advance_branches: list of branches where commit-SHA advancing",
        f"# is EXPECTED (not a regression signal). Diff tool ignores SHA bumps",
        f"# on these branches; still alerts if outcome changes or artifact disappears.",
        f"auto_advance_branches: []",
        f"",
        f"baselines:",
    ]

    for row in rows:
        # Heuristic extraction; UPSTREAM_FORKS.md is human-written so be lenient.
        upstream = row.get("Upstream", "").strip()
        if not upstream or "Upstream" in upstream:
            continue
        fork_link = row.get("Personal fork", "")
        branch_link = row.get("Active branch", "")
        status = row.get("Latest case status", "")
        # Strip markdown link syntax to first text
        m_fork = re.search(r"\[([^\]]+)\]", fork_link)
        m_branch = re.search(r"\[([^\]]+)\]", branch_link)
        fork = m_fork.group(1).strip("`") if m_fork else fork_link
        branch = m_branch.group(1).strip("`") if m_branch else _extract_branch_from_link(branch_link)

        # Status is freeform; we capture first ~120 chars as snapshot value.
        status_short = status[:120].replace("\n", " ").strip()

        # Map upstream name → skill name (heuristic)
        slug = upstream.strip("` ").lower()
        skill_map = {
            "vllm-ascend": "/vllm-ascend-day0",
            "torch-npu": "/torch-npu-day0",
            "transformers": "/transformers-day0",
            "triton-ascend": "/triton-ascend-port",
            "easyr1 (consumer)": "/easyr1-port",
        }
        skill = skill_map.get(slug, f"/{slug}")

        fields = {
            "upstream": upstream.strip("` "),
            "fork": fork.strip(),
            "branch": branch.strip(),
            "status_summary": status_short,
        }
        out.extend(_emit_yaml_block(skill, fields))

    # sglang (issue_only mode) gets a separate manual entry since it has no fork row
    sglang_block = [
        "- skill: /sglang-npu-day0",
        "  upstream: sgl-project/sglang + sgl-project/sgl-kernel-npu",
        "  fork: n/a (no fork — upstream actively maintained)",
        "  branch: n/a",
        '  status_summary: "T28 cold-drive on quay.io/ascend/sglang:main-cann8.5.0-a3 — import smoke PASS; first inference REJECT (RuntimeError 0 active drivers); outcome C_REPORT"',
        "  image_tag: quay.nju.edu.cn/ascend/sglang:main-cann8.5.0-a3",
    ]
    out.extend(sglang_block)

    # Integrated overlay
    integ_block = [
        "- skill: /integrated-overlay-build",
        "  upstream: composed (4 NPU upstreams + EasyR1 master)",
        "  image_tag: easyr1-npu:integrated-20260427",
        "  image_sha256: 044ba0b76183",
        '  status_summary: "T22.7 + T25.5 dual-validation V1.4 GRPO PASS; reward_score=0.013"',
    ]
    out.extend(integ_block)
    out.append("")
    return "\n".join(out)


def _main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--repo-root", required=True)
    args = p.parse_args(argv)
    sys.stdout.write(snapshot(Path(args.repo_root)))
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(_main())
